name: Release
on:
  push:
    tags:
      - "*"
jobs:
  github:
    name: GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Release
        run: |
          ruby \
            -e 'print("## XMLua "); \
                puts(ARGF.read.split(/^## /)[1].gsub(/ {.+?}/, ""))' \
            docs/news/index.md > release-note.md
          title="$(head -n 1 release-note.md | sed -e 's/^## //')"
          tail -n +2 release-note.md > release-note-without-version.md
          gh release create \
            ${GITHUB_REF_NAME} \
            --discussion-category Announcements \
            --notes-file release-note-without-version.md \
            --title "${title}"
        env:
          GH_TOKEN: ${{ github.token }}
